# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-_KZSpALft9a5ZN8riCatcjdrDmZNdk
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # Título con color
# titulo_con_color = "<h1 style='color: red;'>TRABAJO FINAL</h1>"
# st.markdown(titulo_con_color, unsafe_allow_html=True)
# 
# # Título principal
# st.header('RESULTADO PRUEBAS MOLECULARES COVID POR EDAD')
# st.header('INTEGRANTES')
# st.write("Mario Capristan")
# st.write("Joaquin Cardenas")
# 
# # Cargar datos
# def cargar_datos():
#   # Especificar el delimitador
#   data = pd.read_csv("PM_MOL.csv", delimiter=';')
#   return data
# 
# df = cargar_datos()
# 
# # Remover punto y coma
# df.columns = df.columns.str.replace(';', '')
# 
# # Tabla
# st.header('Tabla')
# st.write(df.head(100))
# 
# # Título de filtro
# st.title("Filtro")
# 
# # Filtrar por código
# RESULTADO_filtrado = st.selectbox("FILTRAR POR RESULTADO DE PRUEBA POR EDAD", df['EDAD'].unique())
# # Mostrar datos filtrados
# datos_filtrados = df[df['EDAD'] == RESULTADO_filtrado]
# st.header('RESULTADO FILTRADO')
# st.dataframe(datos_filtrados)
# 
# 
#

!streamlit run app.py & npx localtunnel --port 8501
